### PR TITLE
attempted 2 fixes for logging + pi camera

### PR DESCRIPTION
**Pull request by alec-pinson**
hopefully fixes the 2 issues below
- https://github.com/alec-pinson/TerrariumPI/issues/3
- https://github.com/alec-pinson/TerrariumPI/issues/16

### CODE REVIEW

**Comment by theyosh** [comment]
I am depending on 2 programs in /usr/bin/. So I needed to do:

`ln -s /opt/vc/bin/raspi* /usr/bin/` (I had 1 minute time to do this during startup). So I guess this is something for the Dockerfile.

But, then I seems that the used OpenCV is not correct. I get python errors and I know this is due to different versions....
So the webcam is working with the symlink fix. But, we need to figure out the change with OpenCV.

**Comment by theyosh** [comment]
And I do **not** need: LD_LIBRARY_PATH environment...  I only need the symlinks.

And that reminds me, I do not use the picamera python package anymore. I am using the C apps to get the data.

So, could you also remove the line https://github.com/alec-pinson/TerrariumPI/blob/4.x.y.z-docker/requirements.txt#L54 it is not more needed.

**Comment by theyosh** [comment]
Symlinks for logging are now correct. :+1:

**Comment by alec-pinson** [comment]
> I am depending on 2 programs in /usr/bin/. So I needed to do:
> 
> `ln -s /opt/vc/bin/raspi* /usr/bin/` (I had 1 minute time to do this during startup). So I guess this is something for the Dockerfile.
I'll add this in

> But, then I seems that the used OpenCV is not correct. I get python errors and I know this is due to different versions.... So the webcam is working with the symlink fix. But, we need to figure out the change with OpenCV.

Hmm it will probably be related to these lines, because I didn't want to mess with your requirements.txt for Docker I copy it to container then edit it.
I comment out the `opencv-python-headless` package... I could not get it to work at the time and it was driving me crazy
https://github.com/theyosh/TerrariumPI/blob/6b07f21524d49e69c2300c4528a706200be9672b/Dockerfile#L29-L32
So here instead I install the `python3-opencv` package
https://github.com/theyosh/TerrariumPI/blob/6b07f21524d49e69c2300c4528a706200be9672b/Dockerfile#L66

It sounds like I will need to have another look at trying to get the pip package to install.

**Comment by alec-pinson** [comment]
> > I am depending on 2 programs in /usr/bin/. So I needed to do:
> > `ln -s /opt/vc/bin/raspi* /usr/bin/` (I had 1 minute time to do this during startup). So I guess this is something for the Dockerfile.
> 
> I'll add this in
> 

hmm just a thought actually does this fix it instead?
```
export PATH="/opt/vc/bin:$PATH"
```

**Comment by theyosh** [comment]
> > > I am depending on 2 programs in /usr/bin/. So I needed to do:
> > > `ln -s /opt/vc/bin/raspi* /usr/bin/` (I had 1 minute time to do this during startup). So I guess this is something for the Dockerfile.
> > 
> > 
> > I'll add this in
> 
> hmm just a thought actually does this fix it instead?
> 
> ```
> export PATH="/opt/vc/bin:$PATH"
> ```

Euh, no. I have hardcoded paths in my code...(I know bad practice...)  So that would mean I have to change my python code. We can do that, but for now, I would like to fix it in the Docker file. That is easier for now.

**Comment by alec-pinson** [comment]
Added fix for CO2 sensors to this PR
- https://github.com/alec-pinson/TerrariumPI/issues/18

**Comment by alec-pinson** [comment]
> > > > I am depending on 2 programs in /usr/bin/. So I needed to do:
> > > > `ln -s /opt/vc/bin/raspi* /usr/bin/` (I had 1 minute time to do this during startup). So I guess this is something for the Dockerfile.
> > > 
> > > 
> > > I'll add this in
> > 
> > 
> > hmm just a thought actually does this fix it instead?
> > ```
> > export PATH="/opt/vc/bin:$PATH"
> > ```
> 
> Euh, no. I have hardcoded paths in my code...(I know bad practice...) So that would mean I have to change my python code. We can do that, but for now, I would like to fix it in the Docker file. That is easier for now.

Haha no worries I will get the links added

**Comment by theyosh** [comment]
> But, then I seems that the used OpenCV is not correct. I get python errors and I know this is due to different versions.... So the webcam is working with the symlink fix. But, we need to figure out the change with OpenCV.

Now this is also hot fixed with https://github.com/alec-pinson/TerrariumPI/commit/2e9700e94c5e37ee1a65316a924b51ff19960281

**Comment by theyosh** [comment]
So, I think a new Docker image should be created so that I can test that. And then we can merge this? Or is the build already running...

**Pull request merged**
